config/routes.rb
Playground::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :receipes
  root to: 'receipes#index'
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/aroma.rb
class Aroma < ActiveRecord::Base
  attr_accessible :name

  ##################
  ## Associations ##
  ##################
  has_many :aroma_bundles
  has_many :receipes, through: :aroma_bundles

  #################
  ## Validations ##
  #################
  validates_presence_of :name
end

app/models/aroma_bundle.rb
class AromaBundle < ActiveRecord::Base
  attr_accessible :aroma_id, :receipe_id, :percent

  ##################
  ## Associations ##
  ##################
  belongs_to :aroma, dependent: :destroy
  belongs_to :receipe

  #################
  ## Validations ##
  #################
  validates_numericality_of :percent
  validates_inclusion_of :percent, in: 1..100
  validates_presence_of :percent
end

app/models/author.rb
class Author < ActiveRecord::Base
  attr_accessible :name

  ##################
  ## Associations ##
  ##################
  has_and_belongs_to_many :books
end

app/models/book.rb
class Book < ActiveRecord::Base
  attr_accessible :name


  ##################
  ## Associations ##
  ##################
  has_and_belongs_to_many :authors
end

app/models/receipe.rb
class Receipe < ActiveRecord::Base
  attr_accessible :name, :aroma_bundles_attributes
  PERCENTAGE_LIMIT = 30

  ##################
  ## Associations ##
  ##################
  has_many :aroma_bundles
  has_many :aromas, through: :aroma_bundles

  accepts_nested_attributes_for :aroma_bundles, allow_destroy: true

  #################
  ## Validations ##
  #################
  validate :not_too_much_aromas


  ######################
  ## Instance Methods ##
  ######################
  def not_too_much_aromas
    if overall_aroma_percentage > PERCENTAGE_LIMIT
      self.errors.add(:aroma_percentage, I18n.t('activerecord.errors.receipe.aroma_percentage.too_much'))
    else
      true
    end
  end

  # Returns the overall aroma percentage
  def overall_aroma_percentage
    overall_aroma = self.aroma_bundles.inject(0) do |memo, bundle|
      memo += bundle.percent if bundle.percent.is_a?(Integer) || bundle.percent.is_a?(BigDecimal)
      memo
    end

    return overall_aroma
  end

  # return the highest aroma percentage bundle
  def highest_aroma_percentage_bundle
    # min_percentage_bundle = self.aroma_bundles.inject(nil) do |hap_bundle, bundle|
    #   hap_bundle = bundle if hap_bundle.try(:percentage).to_f < bundle.percentage.to_f
    #   hap_bundle
    # end
    @sorted_bundles ||= self.aroma_bundles.sort{|b1,b2| b1.percent.to_f <=> b2.percent.to_f }

    return @sorted_bundles.last
  end

  # set the highest aroma percentage down to the next valid value
  def fix_highest_aroma_percentage!
    to_much_in_percent = overall_aroma_percentage - PERCENTAGE_LIMIT
    highest_aroma_percentage_bundle.percent -= to_much_in_percent
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/receipes_controller.rb
class ReceipesController < ApplicationController
  # GET /receipes
  # GET /receipes.json
  def index
    @receipes = Receipe.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @receipes }
    end
  end

  # GET /receipes/1
  # GET /receipes/1.json
  def show
    @receipe = Receipe.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @receipe }
    end
  end

  # GET /receipes/new
  # GET /receipes/new.json
  def new
    @receipe = Receipe.new
    @receipe.aroma_bundles.build
    @selectable_aromas = Aroma.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @receipe }
    end
  end

  # GET /receipes/1/edit
  def edit
    @receipe = Receipe.find(params[:id])
    @selectable_aromas = Aroma.all
  end

  # POST /receipes
  # POST /receipes.json
  def create
    @receipe = Receipe.new(params[:receipe])

    respond_to do |format|
      if @receipe.save
        format.html { redirect_to @receipe, notice: 'Receipe was successfully created.' }
        format.json { render json: @receipe, status: :created, location: @receipe }
      else
        @receipe.fix_highest_aroma_percentage!
        format.html do
          @selectable_aromas = Aroma.all
          render action: "new"
        end
        format.json { render json: @receipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /receipes/1
  # PUT /receipes/1.json
  def update
    @receipe = Receipe.find(params[:id])

    respond_to do |format|
      if @receipe.update_attributes(params[:receipe])
        format.html { redirect_to @receipe, notice: 'Receipe was successfully updated.' }
        format.json { head :no_content }
      else
        @receipe.fix_highest_aroma_percentage!
        format.html do
          @selectable_aromas = Aroma.all
          render action: "edit"
        end
        format.json { render json: @receipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /receipes/1
  # DELETE /receipes/1.json
  def destroy
    @receipe = Receipe.find(params[:id])
    @receipe.destroy

    respond_to do |format|
      format.html { redirect_to receipes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/receipes_helper.rb
module ReceipesHelper

  # Return mark if the given bundle_forms bundle should marked as changed
  def mark_as_changed(receipe, bundle_form)
    do_mark = receipe.errors[:aroma_percentage].present?
    do_mark &&= bundle_form.object.id == receipe.highest_aroma_percentage_bundle.id
    return do_mark ? '<b>>>>>>>></b>'.html_safe : ''
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Playground</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/receipes/_form.html.erb
<%= nested_form_for(receipe) do |f| %>
  <% if receipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= t('.errors_occured', count: receipe.errors.count) %>

      <ul>
      <% receipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>

      <% if receipe.errors[:aroma_percentage].present? %>
        Additional:
        <ul>
          <li>Folgendes Bundle wurde angepasst: <%= receipe.highest_aroma_percentage_bundle.aroma.name %></li>
        </ul>
      <% end %>
    </div>
  <% end %>

  <p>
    <%= t('receipes.attributes.name') %>
    <%= f.text_field :name %>
  </p>

  <%= f.fields_for :aroma_bundles do |bundle_form| %>
    <%= mark_as_changed(receipe, bundle_form) %>
    <%= t('receipes.attributes.aroma') %>
    <%= bundle_form.collection_select :aroma_id, selectable_aromas ,:id, :name %>
    <%= bundle_form.text_field :percent, size: 5 %>
    <%= bundle_form.link_to_remove t('receipes.links.remove_aroma') %>
  <% end %>
  <p><%= f.link_to_add t('receipes.links.add_aroma'), :aroma_bundles %></p>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/receipes/edit.html.erb
<h1><%= t('.title', name: @receipe.name) %></h1>

<%= render 'form', receipe: @receipe, selectable_aromas: @selectable_aromas %>

<%= link_to 'Show', @receipe %> |
<%= link_to 'Back', receipes_path %>

app/views/receipes/index.html.erb
<h1>Listing receipes</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @receipes.each do |receipe| %>
  <tr>
    <td><%= receipe.name %></td>
    <td><%= link_to 'Show', receipe %></td>
    <td><%= link_to 'Edit', edit_receipe_path(receipe) %></td>
    <td><%= link_to 'Destroy', receipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Receipe', new_receipe_path %>

app/views/receipes/new.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form', receipe: @receipe, selectable_aromas: @selectable_aromas %>

<%= link_to t('receipes.links.back'), receipes_path %>

app/views/receipes/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_receipe_path(@receipe) %> |
<%= link_to 'Back', receipes_path %>